package com.xebyte.core;

import java.util.*;
import java.util.regex.Pattern;

/**
 * Naming-convention enforcement has been neutered: all validators return
 * empty/ok results so callers don't enforce a project-wide style.
 *
 * <p>Public method signatures and nested types are preserved so existing
 * call sites compile unchanged. Pure utilities (tokenization, prefix
 * extraction) and fact predicates ({@link #isAutoGeneratedGlobalName},
 * {@link #isOsCanonicalGlobalName}, {@link #isUndefinedToUndefined}) still
 * work — they describe what a name is, not what it ought to be.
 */
public final class NamingConventions {

    private NamingConventions() {}

    /**
     * Validate a function name against conventions. Returns list of warnings (empty = valid).
     * PascalCase and verb checks removed — callers use their own naming conventions.
     */
    public static List<String> validateFunctionName(String name, boolean isThunk) {
        return List.of();
    }

    public static final class NameQualityResult {
        public final boolean ok;
        public final String issue;       // short machine-friendly id e.g. "vague_verb"
        public final String message;     // human-readable explanation
        public final String suggestion;  // optional concrete fix hint

        private NameQualityResult(boolean ok, String issue, String message, String suggestion) {
            this.ok = ok;
            this.issue = issue;
            this.message = message;
            this.suggestion = suggestion;
        }

        public static NameQualityResult ok() {
            return new NameQualityResult(true, null, null, null);
        }

        public static NameQualityResult reject(String issue, String message, String suggestion) {
            return new NameQualityResult(false, issue, message, suggestion);
        }
    }

    public static int getVerbTier(String verb) {
        return 0;
    }

    public static boolean isWeakNoun(String token) {
        return false;
    }

    private static final Pattern PASCAL_CASE = Pattern.compile("^[A-Z][a-zA-Z0-9]+$");
    private static final Pattern MODULE_PREFIX = Pattern.compile("^[A-Z]+_[A-Z].*");

    public static List<String> tokenizeFunctionName(String name) {
        if (name == null || name.isEmpty()) return List.of();
        String mainName = name;
        if (MODULE_PREFIX.matcher(name).matches()) {
            mainName = name.substring(name.indexOf('_') + 1);
        }
        if (mainName.isEmpty() || !PASCAL_CASE.matcher(mainName).matches()) return List.of();
        List<String> tokens = new ArrayList<>();
        int start = 0;
        for (int i = 1; i < mainName.length(); i++) {
            if (Character.isUpperCase(mainName.charAt(i))) {
                tokens.add(mainName.substring(start, i));
                start = i;
            }
        }
        tokens.add(mainName.substring(start));
        return tokens;
    }

    public static int countSpecifierTokens(String name) {
        List<String> tokens = tokenizeFunctionName(name);
        return tokens.size() < 2 ? 0 : tokens.size() - 1;
    }

    public static NameQualityResult checkFunctionNameQuality(String name) {
        return NameQualityResult.ok();
    }

    public static String findTokenSubsetCollision(String candidate, Iterable<String> existingNames) {
        return null;
    }

    /** Extract the UPPERCASE_ module prefix, or null if the name has none. */
    public static String extractModulePrefix(String name) {
        if (name == null || !MODULE_PREFIX.matcher(name).matches()) return null;
        return name.substring(0, name.indexOf('_'));
    }

    public static final class TokenizedName {
        public final String name;
        public final String modulePrefix;
        public final Set<String> tokens;

        public TokenizedName(String name) {
            this.name = name;
            this.modulePrefix = extractModulePrefix(name);
            this.tokens = new HashSet<>(tokenizeFunctionName(name));
        }
    }

    public static List<TokenizedName> precomputeTokenized(Iterable<String> names) {
        List<TokenizedName> out = new ArrayList<>();
        if (names == null) return out;
        for (String n : names) {
            if (n != null && !n.isEmpty()) out.add(new TokenizedName(n));
        }
        return out;
    }

    public static String findTokenSubsetCollisionPrecomputed(
            String candidate, List<TokenizedName> precomputed) {
        return null;
    }

    public static String validateHungarianPrefix(String name, String typeName) {
        return null;
    }

    public static List<String> validateGlobalName(String name) {
        return List.of();
    }

    // -----------------------------------------------------------------------
    // Label naming validation
    // -----------------------------------------------------------------------

    public static List<String> validateLabelName(String name) {
        return List.of();
    }

    public static List<String> validatePlateCommentStructure(String plateComment) {
        return List.of();
    }

    public static List<String> validateEnumMemberName(String name) {
        return List.of();
    }

    public static String autoFixFieldPrefix(String fieldName, String typeName) {
        return fieldName;
    }

    public static String applyStructFieldNamingPolicy(String fieldName, String typeName) {
        return fieldName;
    }

    public static boolean isUndefinedToUndefined(String oldType, String newType) {
        return oldType != null && newType != null
                && oldType.startsWith("undefined") && newType.startsWith("undefined");
    }

    static String extractHungarianPrefix(String name) {
        if (name == null || name.length() < 2) return null;

        String[] multiPrefixes = {"lpcsz", "lpsz", "wsz", "ppfn", "apfn", "pp", "pb", "pw",
                "pdw", "pn", "pfn", "ap", "sz", "dw", "fl", "ll", "qw", "ld",
                "ab", "aw", "ad", "an"};
        for (String prefix : multiPrefixes) {
            if (name.startsWith(prefix) && name.length() > prefix.length()
                    && Character.isUpperCase(name.charAt(prefix.length()))) {
                return prefix;
            }
        }

        char first = name.charAt(0);
        if ("bcfnwhld".indexOf(first) >= 0 && name.length() > 1 && Character.isUpperCase(name.charAt(1))) {
            return String.valueOf(first);
        }

        if (first == 'p' && name.length() > 1 && Character.isUpperCase(name.charAt(1))) {
            return "p";
        }

        if (name.startsWith("g_") && name.length() > 3) {
            String afterG = name.substring(2);
            String innerPrefix = extractHungarianPrefix(afterG);
            return innerPrefix != null ? "g_" + innerPrefix : null;
        }

        return null;
    }

    static String toPascalCase(String name) {
        if (name == null || name.isEmpty()) return name;
        StringBuilder result = new StringBuilder();
        for (String part : name.split("_")) {
            if (!part.isEmpty()) {
                result.append(Character.toUpperCase(part.charAt(0)));
                if (part.length() > 1) result.append(part.substring(1).toLowerCase());
            }
        }
        return result.toString();
    }

    private static final Pattern AUTO_GENERATED_GLOBAL = Pattern.compile(
            "^(?:DAT|PTR|UNK|LAB|FLOAT|DOUBLE|UINT|UNDEFINED|s)_[0-9a-fA-F]+(?:\\.[0-9a-fA-F]+)*$"
                    + "|^PTR_DAT_[0-9a-fA-F]+$"
                    + "|^PTR_(?:FUN|LAB)_[0-9a-fA-F]+$",
            Pattern.CASE_INSENSITIVE
    );

    public static boolean isAutoGeneratedGlobalName(String name) {
        if (name == null || name.isEmpty()) return false;
        return AUTO_GENERATED_GLOBAL.matcher(name).matches();
    }

    private static final Set<String> OS_CANONICAL_GLOBAL_NAMES = Set.of(
            "exceptionlist", "stackbase", "stacklimit", "subsystemtib",
            "fiberdata", "arbitraryuserpointer", "self", "environmentpointer",
            "clientid", "activerpchandle", "threadlocalstoragepointer",
            "processenvironmentblock", "lastcomstatus", "tlsslots",
            "vdm", "reservedforntrpc", "instrumentationcallback",
            "kuser_shared_data", "interrupttime", "systemtime",
            "tickcountmultiplier", "ntmajorversion", "ntminorversion"
    );

    public static boolean isOsCanonicalGlobalName(String name) {
        if (name == null || name.isEmpty()) return false;
        return OS_CANONICAL_GLOBAL_NAMES.contains(name.toLowerCase());
    }

    public static boolean isGenericDescriptor(String descriptor) {
        return false;
    }

    public static boolean hasIdaReservedPrefix(String name) {
        return false;
    }

    public static String[] checkGlobalPlateComment(String plateComment) {
        return null;
    }

    public static final int PLATE_LINE_CLIP_THRESHOLD = 80;

    public static int longestPlateLineLength(String plateComment) {
        if (plateComment == null || plateComment.isEmpty()) return 0;
        int max = 0;
        for (String line : plateComment.split("\n", -1)) {
            if (line.length() > max) max = line.length();
        }
        return max;
    }

    public static final class GlobalNameResult {
        public final boolean ok;
        public final String issue;
        public final String message;
        public final String suggestion;

        private GlobalNameResult(boolean ok, String issue, String message, String suggestion) {
            this.ok = ok;
            this.issue = issue;
            this.message = message;
            this.suggestion = suggestion;
        }

        public static GlobalNameResult ok() {
            return new GlobalNameResult(true, null, null, null);
        }

        public static GlobalNameResult reject(String issue, String message, String suggestion) {
            return new GlobalNameResult(false, issue, message, suggestion);
        }
    }

    public static GlobalNameResult checkGlobalNameQuality(String name, String typeName) {
        return GlobalNameResult.ok();
    }
}
